
# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Jasa Backdrop Jakarta
first_name: Jasa Backdrop Jakarta
middle_name: R.
last_name: Name
email: you@example.com
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  jasa backdrop Jakarta - Jasa Interior Kantor

keywords: Jasa interior jakarta, jasa pembuatan backdrop, jasa backdrop jakarta  # add your own keywords or leave empty


# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true

# Dimensions
max_width: 800px


contact_note: >
  You can even add a little note about which of these is the best way to reach you.
# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

google_analytics:  # your Goole Analytics measurement ID (format: G-XXXXXXXXXX)
panelbear_analytics:  # panelbear analytics site ID (format: XXXXXXXXX)

google_site_verification: -RhQJIEgRNxZupAZcVgTYu_9SuD440_kgUXimejNcTI # your google-site-verification ID (Google Search Console)
bing_site_verification:  # out your bing-site-verification ID (Bing Webmaster)

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics:    true  # enables google analytics
enable_panelbear_analytics: false  # enables panelbear analytics
enable_google_verification: true  # enables google site verification
enable_bing_verification:   true  # enables bing site verification
enable_masonry:             true   # enables automatic project cards arangement
enable_math:                true   # enables math typesetting (uses MathJax)
enable_tooltips:            false  # enables automatic tooltip links generated
                                   # for each section titles on pages and posts
enable_darkmode:            true   # enables switching between light/dark modes
enable_navbar_social:       false  # enables displaying social links in the
                                   # navbar on the about page
enable_project_categories:  true   # enables categorization of projects into
                                   # multiple categories
enable_medium_zoom:         true   # enables image zoom feature (as on medium.com)

